export default {
    Sadmin:[
        {
            path:"/main/notice",
            name:"公告主页",
            icon:"NotificationOutlined",
            tag:{noticeTag:false}
        },
        {
            path:"/main/dormitory",
            name:"宿舍管理",
            icon:"MacCommandOutlined",
            tag:{dormitoryTag:false}
        },
        {
            path:"/main/student",
            name:"学生管理",
            icon:"MehOutlined",
            tag:{studentTag:false}
        },
        {
            path:"/main/announcement",
            name:"公告管理",
            icon:"CopyOutlined",
            tag:{announcementTag:false}
        },
        {
            path:"/main/admin",
            name:"管理员管理",
            icon:"UserOutlined",
            tag:{adminTag:false}
        }
    ],
    Cadmin:[
        {
            path:"/main/notice",
            name:"公告主页",
            icon:"NotificationOutlined",
            tag:{noticeTag:false}
        },
        {
            path:"/main/dormitory",
            name:"宿舍管理",
            icon:"MacCommandOutlined",
            tag:{dormitoryTag:false}
        },
        {
            path:"/main/student",
            name:"学生管理",
            icon:"MehOutlined",
            tag:{studentTag:false}
        },
        {
            path:"/main/announcement",
            name:"公告管理",
            icon:"CopyOutlined",
            tag:{announcementTag:false}
        },
        {
            path:"/main/admin",
            name:"管理员管理",
            icon:"UserOutlined",
            tag:{adminTag:false}
        }
    ],
    Badmin:[
        {
            path:"/main/notice",
            name:"公告主页",
            icon:"NotificationOutlined",
            tag:{noticeTag:false}
        },
        {
            path:"/main/dormitory",
            name:"宿舍管理",
            icon:"MacCommandOutlined",
            tag:{dormitoryTag:false}
        },
        {
            path:"/main/student",
            name:"学生管理",
            icon:"MehOutlined",
            tag:{studentTag:false}
        },
        {
            path:"/main/announcement",
            name:"公告管理",
            icon:"CopyOutlined",
            tag:{announcementTag:false}
        },
    ],
    Student:[
        {
            path:"/main/notice",
            name:"公告主页",
            icon:"NotificationOutlined",
            tag:{noticeTag:false}
        },
        {
            path:"/main/student",
            name:"学生管理",
            icon:"MehOutlined",
            tag:{studentTag:false}
        },
    ]
}